version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kanak@123
      POSTGRES_DB: Temprature
    ports:
      - "5432:5432"
